DROP TABLE IF EXISTS STUDENT;
CREATE TABLE STUDENT(
  id INT PRIMARY KEY,
  firstName VARCHAR(250) NOT NULL,
  lastName VARCHAR(250) NOT NULL,
  class VARCHAR(10) NOT NULL,
  nationality VARCHAR(250) NOT NULL
);